version: '3.7'

services:
  shorturl_db:
    image: postgres:15.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.db.prod
    ports:
      - 5433:5432   # задаем порт для подключения к базе из вне
  shorturl_web:
    build: ./urlshortener
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./urlshortener/:/usr/src/shorturl
    ports:
      - 8080:8000
    depends_on:
      - shorturl_db
    env_file:
      - ./.env.prod
  nginx_shorturl:
    image: nginx:1.25.4-alpine
    depends_on:
      - shorturl_web
    ports:
      - "81:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  postgres_data:
  static_data: