# Generated by Django 4.2.11 on 2024-03-12 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeshortedurls',
            options={'ordering': ['-added']},
        ),
        migrations.AddField(
            model_name='freeshortedurls',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='freeshortedurls',
            name='dead_link_time',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeshortedurls',
            name='ttl',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
