# Generated by Django 4.2.11 on 2024-03-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener_app', '0002_alter_freeshortedurls_options_freeshortedurls_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeshortedurls',
            options={'ordering': ['-added'], 'verbose_name': 'Бесплатно укороченные ссылки'},
        ),
    ]
